### ISSUE TITLE
Write JUnit Test Cases

### ISSUE THREAD

**Issue by ohbus** [ohbus/covid-tracker#1]
We need to write JUnit Test Cases for this application

**Comment by Priya103** [comment]
I can do it. Please assign to me

**Comment by ohbus** [comment]
Good luck @Priya103 !

**Comment by Priya103** [comment]
I am unable to push my code... seems I dont have proper acccess[](url)
![image
<img width="1029" alt="Screenshot 2021-01-07 at 9 42 49 PM" src="https://user-images.githubusercontent.com/74041206/103915688-8a45a700-5131-11eb-9772-feec8cd81472.png">
](https://user-images.githubusercontent.com/74041206/103915602-6c784200-5131-11eb-84de-6ae4e2113ede.png)

**Comment by ohbus** [comment]
You need to fork this project and push your changes to your own fork.

Then send your Pull Request to get reviewed.


If you're not sure about OSS contribution norms reach out to me on [hello@subho.xyz](mailto:hello@subho.xyz)

**Comment by Priya103** [comment]
Thanks Ohbus... this will be my first contribution. I have raised PR https://github.com/ohbus/covid-tracker/pull/15
